6---
output:
  word_document: default
  pdf_document: default
  html_document: default
---

##Chapter 3, Example 3.11


###Install
```{r, echo = TRUE}
#another way of getting packages
packages<-function(x){
  x<-as.character(match.call()[[2]])
  if (!require(x,character.only=TRUE)){
    install.packages(pkgs=x,repos="http://cran.r-project.org")
    require(x,character.only=TRUE)
  }
}

packages(fviz_cluster)
packages(gridExtra)
packages(cluster) 
packages(factoextra) # visualization tool
```
###Clusters
```{r, echo = TRUE}
setwd("C:/Book/Chapter3/Examples")
data <-read.csv(file="Ex3.11.csv",head=TRUE,sep=",")

dataNorm <- as.data.frame(scale(data)) #normalizing

#k-means clustering
set.seed(100)
data_K2 <- kmeans(dataNorm, centers = 2, nstart = 25)
fviz_cluster(data_K2, data = dataNorm)
```
###Other clusters
```{r, echo = TRUE}
set.seed(100)
data_K4 <- kmeans(dataNorm, centers = 4, nstart = 25)
fviz_cluster(data_K4, data = dataNorm)
```

###Optimal number of Clusters
```{r, echo = TRUE}
#Optimal clusters (k) Using Elbow method
fviz_nbclust(x = dataNorm,FUNcluster = kmeans, method = 'wss' )

#Optimal clusters (k) Using Average Silhouette Method
fviz_nbclust(x = dataNorm,FUNcluster = kmeans, method = 'silhouette' )
```
###Optimal Clustering
```{r, echo = TRUE}
set.seed(100)
final <- kmeans(dataNorm, centers = 2, nstart = 25)
fviz_cluster(final, data = dataNorm)
```