####Example 4.13

###Install packages
```{r, echo = TRUE}
install.packages("AICcmodavg")
```


###General
```{r, echo = TRUE}
setwd("C:/Book/Chapter4/Examples")
data <-read.csv(file="Ex4.2.csv",head=TRUE,sep=",")
data=data[c(1:83),c(1:4)];
data
```

###General
```{r, echo = TRUE}
setwd("C:/Book/Chapter4/Examples")
data <-read.csv(file="Ex4.2.csv",head=TRUE,sep=",")
data=data[c(1:83),c(1:4)];
data
```

###Model 1 - linear
```{r, echo = TRUE}
b1<-data$InvT;
b2<-data$SOC;
b3<-data$time;
model1 <-lm(data$Capacity~b1+b2+b3)
summary(model1)
```

###Model 2 - quadratic
```{r, echo = TRUE}
b1<-data$InvT;
b2<-data$SOC;
b3<-data$time;
b12<-data$InvT*data$SOC;
b13<-data$InvT*data$time;
b23<-data$SOC*data$time;
b11<-data$InvT*data$InvT;
b22<-data$SOC*data$SOC;
b33<-data$time*data$time;
model2 <-lm(data$Capacity~b1+b2+b3+b12+b13+b23+b11+b22+b33)
summary(model2)
```

###Model selection based on AIC and BIC
```{r, echo = TRUE}
library(AICcmodavg)

models<-list(model1, model2)

#specify model names
mod.names <- c('linear', 'full-quadratic')

#calculate AIC/BIC of each model
aictab(cand.set = models, modnames = mod.names)
bictab(cand.set = models, modnames = mod.names)
```


