---
output:
  word_document: default
  pdf_document: default
  html_document: default
---
###Intro
```{r, echo = TRUE}
#Reference 1https://www.r-bloggers.com/2013/02/pid-control-r/" for the PID design 
```



###Optimal set
```{r, echo = TRUE}
setwd("C:/Book/Chapter4/Examples")
data <-read.csv(file="Ex4.1.csv",head=TRUE,sep=",")
data
plot(data$Set, data$Error, pch = 10, col = 2,xlab="Set",ylab="Error",xlim=c(1,12),ylim=c(9.4,10)) 
```

###Optimization
```{r, echo = TRUE}
install.packages("stats")
```

###Correlation and Optimization
```{r, echo = TRUE}
setwd("C:/Book/Chapter4/Examples")
data <-read.csv(file="Ex4.1.csv",head=TRUE,sep=",")
data
b1=data$Kp;
b2=data$Ti;
b3=data$Td;
b12=data$Kp*data$Ti;
b23=data$Ti*data$Td;
b13=data$Kp*data$Td;
b11=data$Kp^2;
b22=data$Ti^2;
b33=data$Td^2;
qm <-lm(data$Error ~ b1+b2+b3+b12+b23+b13+b11+b22+b33)
summary(qm)
betas<-coefficients(qm)

library(stats)
fun=function(x)
(betas[1]+betas[2]*x[1]+betas[3]*x[2]+betas[4]*x[3]+betas[8]*x[1]^2+betas[9]*x[2]^2+betas[9]*x[3]^2) 
result <- optim(fn=fun, par = c(10,1,0.01), lower=c(9,0.8,0.01), upper=c(10,1.2,0.03), method="L-BFGS-B")
result
```
