---
output:
  word_document: default
  pdf_document: default
  html_document: default
---

##Example 6.3

###Install packages
```{r, echo = TRUE}
install.packages("GA")
```

###Comments of figure 6.3
```{r, echo = TRUE}
#Figure by my mentee, thank you so much!
```

###Genetic Algorithm
```{r, echo = TRUE}
library(GA)

fitness <- function(x){

  #objective function
  fitness_value <- (x[3]+2)*x[2]*x[1]^2;
  
  #constraints
  co1 <- 1 - x[2]^3*x[3]/(71785*x[1]^4);
  co2 <- (4*x[2]^2-x[1]*x[2])/(12566*(x[2] * x[1]^3 - x[1]^4)) + 1/(5108 * x[1]^2) - 1;
  co3 <- 1 - (140.45*x[1])/(x[2]^2*x[3]);
  co4 <- (x[2]+x[1])/1.5 - 1;
  
  #imposing constraints
  fitness_value <- ifelse( co1 <= 0 & co2 <= 0 & co3 <= 0 & co4 <= 0, fitness_value, fitness_value + 1000)
  
  return(fitness_value)
}

GA <- ga(type = "real-valued", 
         fitness =  fitness,
         lower = c(0.05, 0.25, 2), upper = c(2, 1.3, 15),maxiter=1000,popSize=150,monitor=FALSE);
summary(GA)
```

###Install packages
```{r, echo = TRUE}
install.packages("pso")
```

###Particle Swarm Optimization
```{r, echo = TRUE}
library(pso)

fitness <- function(x){

  #objective function
  fitness_value <- (x[3]+2)*x[2]*x[1]^2;
  
  #constraints
  co1 <- 1 - x[2]^3*x[3]/(71785*x[1]^4);
  co2 <- (4*x[2]^2-x[1]*x[2])/(12566*(x[2] * x[1]^3 - x[1]^4)) + 1/(5108 * x[1]^2) - 1;
  co3 <- 1 - (140.45*x[1])/(x[2]^2*x[3]);
  co4 <- (x[2]+x[1])/1.5 - 1;
  
  #imposing constraints
  fitness_value <- ifelse( co1 <= 0 & co2 <= 0 & co3 <= 0 & co4 <= 0, fitness_value, fitness_value + 1000)
  
  return(fitness_value)
}

set.seed(90)
psoptim(rep(NA,3), fn = fitness, lower = c(0.05, 0.25, 2), upper = c(2, 1.3, 15),control=list(maxit=5000))
```

